### ISSUE TITLE
iOS Error: "library not found for -lRNSpeechToTextIos"

### ISSUE THREAD

**Issue by thevishnupradeep** [innFactory/react-native-api-ai#10]
Hi,
I am getting an error "library not found for -lRNSpeechToTextIos" when I am trying to build with xcode. I tried Googling about this error and I got nothing.

**Comment by thevishnupradeep** [comment]
I was able to solve it by adding "react-native-speech-to-text-ios" as a direct dependency.

**Comment by spoeck** [comment]
Alright.
Another `react-native link` or `npm install`could also help for this issue.
