### ISSUE TITLE
Unable to invoke function only in Android

### ISSUE THREAD

**Issue by thevishnupradeep** [innFactory/react-native-api-ai#11]
![screenshot_20170926-172509](https://user-images.githubusercontent.com/5638461/30866387-20f501f4-a2ea-11e7-98aa-b51cd3835ab9.png)

This is how my dependencies looks like.

dependencies {
    // From node_modules
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile project(':react-native-billing')
    compile project(':react-native-spinkit')
    compile project(':react-native-vector-icons')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-calendar-events')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile 'com.facebook.react:react-native:+'
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile "com.google.android.gms:play-services-base:11.2.2"
    compile 'com.google.firebase:firebase-core:11.2.2'
    compile 'com.google.firebase:firebase-messaging:11.2.2'
    compile 'com.google.firebase:firebase-auth:11.2.2'
    compile 'com.google.firebase:firebase-database:11.2.2'
    compile 'com.google.firebase:firebase-crash:11.2.2'
    compile project(':react-native-api-ai')
}

Also, I have `apply plugin: 'com.google.gms.google-services'`
at the end of my app.gradle.

**Comment by spoeck** [comment]
The `compile project(':react-native-api-ai')` dependency is definitely missing.
Try to link your project again with `react-native link`. It should be there after that command and also in the settings file.

**Comment by thevishnupradeep** [comment]
Thank you for your reply. I can assure you I have done `react-native link`. In fact, you can see the `compile project(':react-native-api-ai')` at the end of the dependencies.

I just tried relink the module and it still doesn't work.

**Comment by thevishnupradeep** [comment]
I just noticed one thing. I have `ApiAi.setConfiguration('<API_KEY>', ApiAi.LANG_ENGLISH);` in the constructor function of my component. and `ApiAi.requestQuery('PHONE_CONVO_BEGIN', this.setAPIResults, this.setAPIError);` in the componentDidMount method. setConfiguration produces no error

**Comment by spoeck** [comment]
Ok, then your decencies should be right.

Can you show me the call of `requestQuery`?
Make sure you have three Parameters: `requestQuery("some text", r=>console.log(r), e=>console.log(e))`

**Comment by thevishnupradeep** [comment]
I can assure you that the code is correct as it is working in iOS perfectly. The issue happens only in Android.

`ApiAi.requestQuery('PHONE_CONVO_BEGIN', this.setAPIResults, this.setAPIError);`

**Comment by spoeck** [comment]
Can you try `ApiAi.requestQuery('PHONE_CONVO_BEGIN', r=>this.setAPIResults(r), e=>this.setAPIError(e));` just to make sure that no callback is null?

**Comment by thevishnupradeep** [comment]
Still the same error. But there are some changes in the error report.
![screenshot_20170927-171408](https://user-images.githubusercontent.com/5638461/30915383-b4a1fcf0-a3a7-11e7-8d6b-7dc671aba04f.png)

**Comment by spoeck** [comment]
Unfortunately, I'm on the way to the react con in Alicante and I don't have my notebook with me. Can you try the sample app of the example folder. Does requestQuery work or at least start listening on android?

**Comment by thevishnupradeep** [comment]
Hi, 
I just did that and the same error happened.

**Comment by spoeck** [comment]
I will have a deeper look into this issue when I'm back in office next Monday!

**Comment by thevishnupradeep** [comment]
I just did some googling on my own on this issue. This issue seems to be affecting many libraries like this. Then I went to official API AI android client and found [this](https://github.com/api-ai/apiai-android-client/issues/34).

The solution was to replace `compile 'ai.api:libai:1.4.8'` with `compile('ai.api:libai:1.4.8') {
        exclude module: 'log4j-core'
    }`.

And I can confirm that it is working.

**Comment by thevishnupradeep** [comment]
However, there is another issue right now. In iOS, the result is an object but in Android the result is returned as a JSON string

**Comment by spoeck** [comment]
I just was trying to reproduce your issue and didn't get any error while invoking requestQuery. It might be related to your android configuration. But anyway, thank you for your research and solving this problem!

For following issue:

> However, there is another issue right now. In iOS, the result is an object but in Android the result is returned as a JSON string

> 

I open a separate one #13
