### ISSUE TITLE
while running the app its showing error "cann't set read only property" when i have just  imported  the package "react-native-api-ai". 

### ISSUE THREAD

**Issue by Aashish-1008** [innFactory/react-native-api-ai#12]

**Comment by spoeck** [comment]
@Aashish-1008 

Could you please give me more info? Did the error appear on iOS or Android? Where are you make the import - in a react component?

**Comment by Aashish-1008** [comment]
this error comes in both the platforms when i m trying to import the module in main component of my app.

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Button
} from 'react-native';

import ApiAi from "react-native-api-ai",    // if i didn't import this module everything works fine.

I have done linking part also.

**react-native link react-native-api-ai**

**Comment by spoeck** [comment]
Strange... Could you post the redscreen? And which react-native version do you use?
