### ISSUE TITLE
hey @spoeck, is there is any way to send additional parameter to api.ai intents ( except speech text ) i.e like i want to send access_token to my intent which later will send this token to my node web-hook

### ISSUE THREAD

**Issue by Aashish-1008** [innFactory/react-native-api-ai#14]

**Comment by spoeck** [comment]
You can try using the context:
```javascript
const contexts = [{
  name: "config",
  lifespan: 1,
  parameters: {
      access_token: "your access token"
  }
}];

ApiAi.setContexts(contexts);
```

**Comment by Aashish-1008** [comment]
Cann't we do this using events which attached to intent  and then we will set the event data to params.

**Comment by spoeck** [comment]
I could implement a method which sets a "permanent" context: 
```javascript
ApiAi.setPermanentContexts([{name: "sample", parameters: {access_token: "your access token"}])
```
Then I would set this context on every request with lifespan 1.

Would this help you?

**Comment by Aashish-1008** [comment]
perfect thanks !!
**One more thing** 
const contexts = [{
  name: "config",
  lifespan: 1,
  parameters: {
      access_token: "your access token"
  }
}];

Using set contexts i able to trigger my corresponding intent. But i don't know how to get those send parameter to my node web hook.

**Comment by spoeck** [comment]
Ok.. I will implement `setPermanentContexts` next weekend.

I've not done something with webhooks so far but the whole contexts should accessible via the request object `req` of the official example:
https://api.ai/docs/getting-started/basic-fulfillment-conversation

**Comment by Aashish-1008** [comment]
Thanks !!

**Comment by Aashish-1008** [comment]
Hey, i guess sending events is not present in this module.
Can you add support for that also.
It will be highly appreciated. Thanks.

**Comment by spoeck** [comment]
Yepp I'm planning to add events, but I stuck on one issue a little bit. It will take some more time for events and it is not on the top position on my todo list. If you need events urgent I recommend following workaround:

1. make an intent
2. add a context for this intent with the name of your event
3. set this context in your app via ApiAi.setContext
4. call ApiAi.requestQuery("", ()=>{},()=>{}) with an empty query
5. may ignore fulfillment speech

This is actually the same as request an event.

**Comment by Aashish-1008** [comment]
I found a another way to send events.
As api.ai is totally exposed via api endpoints .So we can also send events by making a api post request to api.ai .

This is code:
var data = {
        "event": {
          "name": "WELCOME",
          "data": {
            "token": "aashish.."
          }
        },
        "timezone": 'America/New_York',
        'lang': "en",
        "sessionId": currentSessionId
      }

      fetch("https://api.api.ai/api/query?v=20150910", {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer DEVELOPER_ACCESS_TOKEN',
            'charset': "utf-8"
          },
          body: JSON.stringify(data)
        })
        .then(function(response) {
          var json =  response.json().then(function(res){
            console.log('---rrr--',res)
          })
        })
        .then(function(data) {
          console.log(data)
        });

      }, error=>console.log(error))

**Comment by Arafath-misree** [comment]
Guys does this support latest version of react-native i am getting an error ld: library not found for -lRNSpeechToTextIos
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by spoeck** [comment]
@Aashish-1008 
Thanks for your fetch-method. I implemented it in ApiAi. With version v1.4.0 your have your permanentContext and the ability to requestEvents!

@Arafath-misree 
I will look into this problem. This is also total out of context of this issue, so I will put your description to a new one and close this one.
