### ISSUE TITLE
Getting the following exception if I build my project for android

### ISSUE THREAD

**Issue by noorulrazvi-alef** [innFactory/react-native-api-ai#6]
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE
        File1: /Users/nrazvi/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.2/c707664e020218f8529b9a5e55016ee15f0f82ac/log4j-core-2.2.jar
        File2: /Users/nrazvi/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.2/d7ef6ad7ff0711dd12fe409d62d72d6ed14516e0/log4j-api-2.2.jar

**Comment by jona7o** [comment]
I think you use some other libaries in your project? You must define a merge strategy in your maven/gradle build. @spoeck do you think the same?

**Comment by noorulrazvi-alef** [comment]
Thank you for your reply..Yes, I updated the packagingOptions in my app's build.gradle and things are started working now.
