### ISSUE TITLE
Can we get the text spoken when doing ApiAi.startListening?

### ISSUE THREAD

**Issue by rajasaur** [innFactory/react-native-api-ai#9]
Hi, 
Thanks for the project, helps us get a great jumpstart.

We are developing a chat application using APIAI as the backend and were wondering if there is any hook available to get the text when doing ApiAI.startListening. Typically as a chat user, it will be good to show the result of what the user spoke before getting the response from ApiAI. 

Our chat app (without this) was doing a separate Google Speech-to-text plugin to do the conversion first and then sending it to the backend engine, but now that the ApiAI.startlistening is available, it makes sense to just let the backend engine do the speech to text itself, but we are not able to get the text before the response is available.

I looked inside to see if there are any hooks available, but doesnt look like it. Are there any other ways to achieve this?

Thanks!

**Comment by spoeck** [comment]
Hi, thanks for using our lib ;)

You can still use your Speech-To-Text plugin and just send the text to api.ai:
```javascript
  ApiAi.requestQuery("Some text for your api-ai agent", result=>console.log(result), error=>console.log(error));
```

For iOS i do the same thing in background with `react-native-speech-to-text-ios`.

Api.ai has it's own speech-to-text-engine but it's deprecated and was removed on the javascript client a few days ago - I think android will follow soon. I recommend to use the device speech-to-text functionality or any other service.

**Comment by rajasaur** [comment]
Thanks for the quick response @spoeck . We will use the requestQuery to do the conversion and send the text request itself.. Thanks again!
